[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.0.1"
authors = [
    {name = "Andreas Rieger", email = "dev@rieger.digital"},
]


[tool.setuptools]
